# This file is a specification for our Frontend API using OpenAPI v3.
openapi: 3.0.1
info:
  title: CTF Frontend API
  description: Frontend API for querying challenge sets, challenges, etc. from the CTF platform.
  version: 0.2.0
servers:
  - url: 'https://ctf.cyberliteracyforall.com'
paths:
  /api/challenge-sets:
    get:
      responses:
        '200':
          description: List of challenge sets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChallengeSet'
  /api/challenge-sets/{challenge-set-slug}:
    get:
      parameters:
        - name: challenge-set-slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Challenge set was found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChallengeSet'
        '404':
          description: Challenge set was not found
  /api/challenge-sets/{challenge-set-slug}/challenges:
    get:
      parameters:
        - name: challenge-set-slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of challenges for challenge set
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChallengeSet'
        '404':
          description: Challenge set was not found
  /api/challenge-sets/{challenge-set-slug}/challenges/{challenge-slug}:
    get:
      parameters:
        - name: challenge-set-slug
          in: path
          required: true
          schema:
            type: string
        - name: challenge-slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Challenge was found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Challenge'
        '404':
          description: Challenge was not found
  /api/challenge-sets/{challenge-set-slug}/challenges/{challenge-slug}/docs/{doc-path}:
    get:
      parameters:
        - name: challenge-set-slug
          in: path
          required: true
          schema:
            type: string
        - name: challenge-slug
          in: path
          required: true
          schema:
            type: string
        - name: doc-path
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Documentation was found
          content:
            text/markdown: {}
        '404':
          description: Documentation was not found
  /api/top-challenges:
    get:
      responses:
        '200':
          description: List of top challenges
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChallengePlayCountList'
  /api/user/environments:
    get:
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of environments running for this user
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/UserEnvironmentInfo'
    post:
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEnvironmentRequest'
      responses:
        '200':
          description: Environment was created for user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateEnvironmentResponse'
  /api/user/environments/{environment-id}/submit:
    post:
      security:
        - bearerAuth: []
      parameters:
        - name: environment-id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Flag was accepted
        '400':
          description: Flag was not accepted
        '404':
          description: Challenge was not found

components:
  schemas:
    ChallengeSet:
      type: object
      required:
        - id
        - slug
        - name
        - description
        - challenges
      properties:
        id:
          type: string
          format: uuid
        slug:
          type: string
        name:
          type: string
        description:
          type: string
    Challenge:
      type: object
      required:
        - id
        - slug
        - name
        - description
        - documentation
        - features
        - flag
      properties:
        id:
          type: string
          format: uuid
        slug:
          type: string
        name:
          type: string
        description:
          type: string
        documentation:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              path:
                type: string
              order:
                type: integer
        features:
          type: array
          items:
            type: string
            enum:
              - flag
        flag:
          type: object
          properties:
            type:
              type: string
              enum:
                - none
                - static
          oneOf:
            - properties:
                type:
                  type: string
                  enum:
                    - none
            - properties:
                type:
                  type: string
                  enum:
                    - static
                value:
                  type: string
    ChallengePlayCount:
      type: object
      required:
        - challengeSet
        - challenge
        - playCount
      properties:
        challengeSet:
          $ref: '#/components/schemas/ChallengeSet'
        challenge:
          $ref: '#/components/schemas/Challenge'
        playCount:
          type: integer
    ChallengePlayCountList:
      type: array
      maxItems: 5
      items:
        $ref: '#/components/schemas/ChallengePlayCount'
    UserEnvironmentInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        challengeSetSlug:
          type: string
        challengeSlug:
          type: string
    CreateEnvironmentRequest:
      type: object
      properties:
        challengeSetSlug:
          type: string
        challengeSlug:
          type: string
      required:
        - challengeSetSlug
        - challengeSlug
    CreateEnvironmentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
        - id

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
