apiVersion: ctf.acasi.info/v1alpha1
kind: EnvTemplate
metadata:
  name: pentesting-hash-identifier
spec:
  pods:
    - metadata:
        name: penimage
        labels:
          app: penimage
      spec:
        containers:
          - name: penimage
            image: ghcr.io/acasi-ctf/challenges/pentesting/hash-identifier:latest
  services:
    - metadata:
        name: penimage-termproxy
      spec:
        selector:
          app: penimage
        ports:
          - port: 22
            ctfExpose: Termproxy
