apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: ctf-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-frontend
  strategy: { }
  template:
    metadata:
      labels:
        app: ctf-frontend
    spec:
      containers:
        - image: ghcr.io/acasi-ctf/ctf/frontend:latest
          name: frontend
          resources: { }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctf-frontend
  name: frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ctf-frontend
