apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations: {}
spec:
  tls:
    - hosts: [ ]
  rules:
    - host: ctf.example.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ctf-ui
                port:
                  name: http
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ctf-frontend
                port:
                  name: http
          - path: /TermproxyService/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ctf-termproxy
                port:
                  number: 1235
