apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  labels:
    app: ctf-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-operator
  strategy: { }
  template:
    metadata:
      labels:
        app: ctf-operator
    spec:
      serviceAccountName: operator
      containers:
        - image: ghcr.io/acasi-ctf/ctf/operator:latest
          name: operator
          resources: { }
          volumeMounts:
            - name: auth-key-public
              mountPath: /secrets/auth-key-public
              readOnly: true
      volumes:
        - name: auth-key-public
          secret:
            secretName: auth-key-public
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctf-operator
  name: operator
spec:
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 1234
  selector:
    app: ctf-operator
