apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  labels:
    app: ctf-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-operator
  strategy: { }
  template:
    metadata:
      labels:
        app: ctf-operator
    spec:
      serviceAccountName: operator
      containers:
        - image: ghcr.io/acasi-ctf/ctf/operatorkt:latest
          name: operator
          resources: { }
          env:
            - name: DB_PATH
              value: /data/operator.db
          volumeMounts:
            - name: auth-key-public
              mountPath: /secrets/auth-key-public
              readOnly: true
            - name: database
              mountPath: /data
      volumes:
        - name: auth-key-public
          secret:
            secretName: auth-key-public
        - name: database
          persistentVolumeClaim:
            claimName: ctf-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctf-operator
  name: operator
spec:
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 1234
  selector:
    app: ctf-operator
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: operator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
