apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "secrets" ]
    verbs: [ "create", "delete", "deletecollection", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "statefulsets" ]
    verbs: [ "create", "delete", "deletecollection", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses", "networkpolicies" ]
    verbs: [ "create", "delete", "deletecollection", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "ctf.acasi.info" ]
    resources: [ "environments", "envtemplates" ]
    verbs: [ "create", "delete", "deletecollection", "get", "list", "patch", "update", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator
subjects:
  - kind: ServiceAccount
    name: operator
