apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ctf-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-ui
  strategy: { }
  template:
    metadata:
      labels:
        app: ctf-ui
    spec:
      containers:
        - image: ghcr.io/acasi-ctf/ctf/ui:latest
          imagePullPolicy: Always
          name: ui
          resources: { }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctf-ui
  name: ui
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ctf-ui
