apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctf-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ctf-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctf-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ctf-operator
subjects:
- kind: ServiceAccount
  name: ctf-operator
---
apiVersion: v1
data:
  id_rsa: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdG
    RqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3Rj
    bgpOaEFBQUFBd0VBQVFBQUFZRUF5MnMrUkVTYU9IVnovYzMyaCtjbUxQTFpFNHU2VUNUeE
    l5M0Y2VFE1N0Z6K3NDajgzOERlClQyVVQ3cVZuYWMrUHNCdXJWSVYyRlQ5SGpBSTlVOSt1
    NFV6N0htUEVycVpldDIxY1JjbllLNllVS1FnZ3ZQMC9nS04yaDQKRzRoS2NVeFBRdHNiTU
    dtcExuSHU2Y1daeWwycFV3b0Nnb2dvbkRWeUdJL3hJRFQ0bkpoV1FKWWlBczlab2hZZlNv
    RXVMTgppRW8zUlJ3MndQT0taQXVpd1U4L3BzRnAvcG5zei9ibVU4Q2cvTmlBTzVKWGlrdG
    1BampyMjZpemtuZzB0ajJFdys3TGlTCmsxelZtUlZmZFdoeFJjTGpiQ2pxZWxyYm1rNnR2
    VmtGOElrWUFYK2YrZjBmZVZUTW94MEZISjdzbTBZUFdxbmZvWmlDT3MKUDlkaGpMaC84SU
    RjVUIyUEI0dHJSdFRFYzd0Y21TVmFBQThwdS9tYWpkdlRSVGJkbU9OVFpIWlJXeUJyM25G
    SXA3SjdHagpIRjY2dUhPbklzbmxMdUNYaERRSDZabGdUTmZmNk9yMWhSVTBqakJobVc5dG
    ZlMlZQREtJZThLclU3ZzJPejE3c0Foc21XCkJBT1FFTDhIWnlZZHR6VmtCWmVzcVVWdEt3
    NmdkWU1pOEpZTjB3ODFBQUFGaU1vWmkwcktHWXRLQUFBQUIzTnphQzF5YzIKRUFBQUdCQU
    10clBrUkVtamgxYy8zTjlvZm5KaXp5MlJPTHVsQWs4U010eGVrME9leGMvckFvL04vQTNr
    OWxFKzZsWjJuUApqN0FicTFTRmRoVS9SNHdDUFZQZnJ1Rk0reDVqeEs2bVhyZHRYRVhKMk
    N1bUZDa0lJTHo5UDRDamRvZUJ1SVNuRk1UMExiCkd6QnBxUzV4N3VuRm1jcGRxVk1LQW9L
    SUtKdzFjaGlQOFNBMCtKeVlWa0NXSWdMUFdhSVdIMHFCTGl6WWhLTjBVY05zRHoKaW1RTG
    9zRlBQNmJCYWY2WjdNLzI1bFBBb1B6WWdEdVNWNHBMWmdJNDY5dW9zNUo0TkxZOWhNUHV5
    NGtwTmMxWmtWWDNWbwpjVVhDNDJ3bzZucGEyNXBPcmIxWkJmQ0pHQUYvbi9uOUgzbFV6S0
    1kQlJ5ZTdKdEdEMXFwMzZHWWdqckQvWFlZeTRmL0NBCjNGQWRqd2VMYTBiVXhITzdYSmts
    V2dBUEtidjVtbzNiMDBVMjNaampVMlIyVVZzZ2E5NXhTS2V5ZXhveHhldXJoenB5TEoKNV
    M3Z2w0UTBCK21aWUV6WDMranE5WVVWTkk0d1labHZiWDN0bFR3eWlIdkNxMU80TmpzOWU3
    QUliSmxnUURrQkMvQjJjbQpIYmMxWkFXWHJLbEZiU3NPb0hXREl2Q1dEZE1QTlFBQUFBTU
    JBQUVBQUFHQkFKMUtBR3lqS3lpcTBSU1lWSjlEUVlhU0JQCjRURmU1d2tqQmtiVnJrTWtH
    c3FwYW1LdG9NOVJrcERCK0VzQkRtR0xIUXcwcm9vNlRNT0ZOdlMrSjEzSENEcU0wWDBmWk
    YKMklrMnU1bU8rR0xQMlZqYzJ3dW5PcG9LUzFWK0hhSWMyM2RyWTRXNjYwbE1lLyt6K3h0
    amYrOGpXdVVNQ0Q3ZnJUYkxUSApZR2hKN1U2UWtHa0NiYXdFanNkQkdkTHZUamdJOTQ2NE
    c1empDbVlBVDU1bEJaS2R1VVJKUkVpeE5IVTFQQlovbjZvalR0CjlGaVA4b0dYWi9DQ1lz
    L0h1T0tOYjZBRlF5c1pvS2Ntdm50aXhZd0diSTllK2VNcmJTSFBNZjdYTXV4aTFxNlJhSC
    ticmMKdHY2Y3ZpeGxvTGFwRGdxampHMFlFU3Uvd0JGM2Npd096cTRJZDAyK3hvTHh0M015
    U0tSZ0hNaWg5YTFZQ0ROeFV1OHVpWgozUktUaHlXRDUrKzNGaUhWeHVxSXg0SEJMbVVlUz
    lERFU1L1dua1U4cFRIWDhqckhYb1h4WDZKZCtRM3BKdzZVUEhLaFJSClJiNUJNQ3hFaTA3
    V0UwNEhjWEZORmRiRHJpQmFIUUsvczZ5QTEvNW5aL3Bic08xVUQ4OWlRRW83YVRDMUIzaT
    QrTklRQUEKQU1COTByM0E1OGN3ejZaZytUSU02cW9nZDJIR0ZtZjZtK2tXdis0WEVkQjBQ
    akxhSSs5WXU5YjJxVFpPd2xCM1h3YXlQSAp2ZDRUV25tS21kTnRSRGdMSXdrYkxGS3A1UU
    Z6QTZhSGpUQmJuOXk1VGp3VnZUQ1JXZ0QzY01sYUJCTTZLN1JoMk1NMTNuClp6RU1kZm5p
    MERCU3VGV25INHB2M2ZFNzY2bVBtUTh5UTE0blVXMndGN1VkVGNabzNHZFdrZDM5K1lLck
    lpd1FCSGozejQKTjNibncrSHNRQUtsWEVlalUrL3BoV0VCazNxSkVzZkY0MEIyOFlmN2NG
    SzJYOUNvSUFBQURCQVBtK0NXWUxDN05aeU56WAozNUo2SzgvQkw5Nk9rQW1HaG81UjF4Uk
    1VMVRCazhPdURvd3VZSXMzZWlGNCtKV1JaYzcwNmlxbDIwdm1CZGhSVjZkUWI2CnZZZGZM
    TmxBUDRjY08wMzBidUlrQXNHelZRRDhrMjFkcGNudjZsNXhZSS9aS2R2MWFNdU5LU2VSam
    F4Q0RGMjZkdVAvb0UKUjNDcTVSRjg0WEExdlA5VWlzRmtSclJVUjBhNmdvQ3ZueEhwS1dI
    SEtsQk9IbTJRN0M4YjFOc1dmK2x0L2Z3UTNrbTMyTQpvNC9UYVpQSGIzakNxWjhLSEJZOT
    JEZnJZUXh2TG9DUUFBQU1FQTBJUVJEMFBwcXIzSWZpRENIZ0NBQnQwSEM1YnRyT2hHCjg5
    Z3p3MWNNWWtOeS90MDJYV2VVTDRoajgwZWhpQi92d0RkemhHWGREaDRVTll6Ulg0am5MaU
    tLVmtlZlM1UzRNWmkyR00KOFdYb0ZzSHJxak9wekhRbmdUNkJNSWRjRFhjTk4ydW51TzM3
    Z2FpZ1pZMzNZL0VpS0lPaU40dDRmU2xCb2pGNE1SSnFwVQovc2lDRVJTOFVYOGhiTUh0UE
    tIQjlKNFFqMCsxRHFsVW04ZjY2VFpQUEtFek5VSTByWHpDNWFiNUNTT3UzYlZtQTNjb3hj
    ClNQdy9oL3M1VXFKVUROQUFBQUQyeG5iM0psYm1ObFFGVnNkSEp2YmdFQ0F3PT0KLS0tLS
    1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: ctf-auth-key-private-m6m8t4b8gm
type: Opaque
---
apiVersion: v1
data:
  id_rsa.pub: |
    c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FETGF6NUVSSm80ZFhQOX
    pmYUg1eVlzOHRrVGk3cFFKUEVqTGNYcE5EbnNYUDZ3S1B6ZndONVBaUlB1cFdkcHo0K3dH
    NnRVaFhZVlAwZU1BajFUMzY3aFRQc2VZOFN1cGw2M2JWeEZ5ZGdycGhRcENDQzgvVCtBbz
    NhSGdiaUVweFRFOUMyeHN3YWFrdWNlN3B4Wm5LWGFsVENnS0NpQ2ljTlhJWWovRWdOUGlj
    bUZaQWxpSUN6MW1pRmg5S2dTNHMySVNqZEZIRGJBODRwa0M2TEJUeittd1duK21lelA5dV
    pUd0tEODJJQTdrbGVLUzJZQ09PdmJxTE9TZURTMlBZVEQ3c3VKS1RYTldaRlY5MWFIRkZ3
    dU5zS09wNld0dWFUcTI5V1FYd2lSZ0JmNS81L1I5NVZNeWpIUVVjbnV5YlJnOWFxZCtobU
    lJNncvMTJHTXVIL3dnTnhRSFk4SGkydEcxTVJ6dTF5WkpWb0FEeW03K1pxTjI5TkZOdDJZ
    NDFOa2RsRmJJR3ZlY1VpbnNuc2FNY1hycTRjNmNpeWVVdTRKZUVOQWZwbVdCTTE5L282dl
    dGRlRTT01HR1piMjE5N1pVOE1vaDd3cXRUdURZN1BYdXdDR3laWUVBNUFRdndkbkpoMjNO
    V1FGbDZ5cFJXMHJEcUIxZ3lMd2xnM1REelU9IGxnb3JlbmNlQFVsdHJvbgo=
kind: Secret
metadata:
  name: ctf-auth-key-public-b2gt262278
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctf-operator
  name: ctf-operator
spec:
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 1234
  selector:
    app: ctf-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctf-termproxy
  name: ctf-termproxy
spec:
  ports:
  - name: grpc
    port: 1234
    protocol: TCP
    targetPort: 1234
  - name: grpc-web
    port: 1235
    protocol: TCP
    targetPort: 1235
  selector:
    app: ctf-termproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ctf-operator
  name: ctf-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-operator
  strategy: {}
  template:
    metadata:
      labels:
        app: ctf-operator
    spec:
      containers:
      - image: ghcr.io/acasi-ctf/ctf/operator:latest
        name: operator
        resources: {}
        volumeMounts:
        - mountPath: /secrets/auth-key-public
          name: auth-key-public
          readOnly: true
      serviceAccountName: ctf-operator
      volumes:
      - name: auth-key-public
        secret:
          secretName: ctf-auth-key-public-b2gt262278
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ctf-termproxy
  name: ctf-termproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-termproxy
  strategy: {}
  template:
    metadata:
      labels:
        app: ctf-termproxy
    spec:
      containers:
      - image: ghcr.io/acasi-ctf/ctf/termproxy:latest
        name: termproxy
        resources: {}
        volumeMounts:
        - mountPath: /secrets/auth-key-private
          name: auth-key-private
          readOnly: true
      volumes:
      - name: auth-key-private
        secret:
          secretName: ctf-auth-key-private-m6m8t4b8gm
