---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Modified for CTF
# Taken from
# https://github.com/github/super-linter/blob/master/TEMPLATES/.markdown-lint.yml

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 400            # Line length 80 is far to short
MD024:
  allow_different_nesting: true
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines
